dist: jammy
language: bash
services: docker

env:
  matrix:
    - TIKA_DOCKER_VERSION=2.6.0.2 TIKA_VERSION=2.6.0

script:
  - ./docker-tool.sh build $TIKA_DOCKER_VERSION $TIKA_VERSION
  - ./docker-tool.sh test $TIKA_DOCKER_VERSION $TIKA_VERSION
